name: CI/CD FastAPI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
      
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests
      run: python test.py

    - name: Kill app
      run : |
        echo "$EC2_SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-34-241-171-80.eu-west-1.compute.amazonaws.com "screen -S api_session -X quit"
      env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Update and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-34-241-171-80.eu-west-1.compute.amazonaws.com "cd ~/fastapi-cicd && git pull origin main && screen -dmS api_session python3 api.py"
