name: CI/CD FastAPI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
      
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests
      run: python test.py

    - name: Kill app
      run : |
        echo "$EC2_SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        if ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-52-214-211-49.eu-west-1.compute.amazonaws.com "pgrep -f 'screen -S api_session'"; then
        echo "App is running, proceeding to kill it"
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-52-214-211-49.eu-west-1.compute.amazonaws.com "screen -S api_session -X quit"
        else
          echo "App is not running"
        fi
      env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Check if MLflow UI is running
      run: |
        if ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-52-214-211-49.eu-west-1.compute.amazonaws.com "pgrep -f 'mlflow ui'"; then
          echo "MLflow UI is running, killing it"
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-52-214-211-49.eu-west-1.compute.amazonaws.com "pkill -f 'mlflow ui'"
        else
          echo "MLflow UI is not running"
        fi

    - name: Update and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-52-214-211-49.eu-west-1.compute.amazonaws.com "cd ~/fastapi-cicd && git pull origin main && screen -dmS api_session sh -c 'python3 api.py'"
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@ec2-52-214-211-49.eu-west-1.compute.amazonaws.com "cd ~/mlflow && git pull origin main && screen -dmS api_session sh -c 'mlflow ui -h 0.0.0.0 -p 5000'"
