name: CI/CD FastAPI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EC2_ADDRESS: ${{ secrets.EC2_ADDRESS }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
      
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests 
      run: python test.py

    - name: Check if project exists, create if it doesn't
      run: |
        echo "$EC2_SSH_KEY" > /.ssh/ssh_key.pem
        chmod 600 /.ssh/ssh_key.pem
        ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS "[ -d ~/fastapi-cicd ] && echo 'API Exists' || git clone https://github.com/adubig24/fastapi-cicd.git"
        ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS "[ -d ~/mlflow ] && echo 'MLFlow Exists' || mkdir mlflow"

    - name: Stop API if running
      run : |
        echo "$EC2_SSH_KEY" > /.ssh/ssh_key.pem
        chmod 600 /.ssh/ssh_key.pem
        if ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS "source ~/.profile && pgrep -f 'api'"; then
        echo "App is running, proceeding to kill it"
        ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$EC2_ADDRESS "source ~/.profile && screen -S api -X quit"
        else
          echo "App is not running"
        fi

    - name: Stop MLFlow if running
      run: |
        if ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS "source ~/.profile && pgrep -f 'mlflow'"; then
          echo "MLflow UI is running, killing it"
          ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS "source ~/.profile && pkill -f 'mlflow'"
          ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS "source ~/.profile && pkill -f 'mlflow'"
        else
          echo "MLflow UI is not running"
        fi

    - name: Update and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i /.ssh/ssh_key.pem ubuntu@$EC2_ADDRESS "source ~/.profile && sh ~/fastapi-cicd/script.sh"