name: Python Test

on:
  push:
    branches:
      - main  # Change to your default branch name if it's different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests
      run: python test.py


  deploy:
    needs: test  # Wait for the 'test' job to finish before deploying
    runs-on: ubuntu-latest
    steps:
    - name: Copy SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$EC2_SSH_KEY" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
      
    - name: Deploy to EC2
      run: |
        ssh -o "StrictHostKeyChecking=accept-new" -i ~/.ssh/ec2.pem ubuntu@ec2-18-201-138-117.eu-west-1.compute.amazonaws.com "cd ~/fastapi-cicd && git pull origin main && kill -f 'python3 api.py' && python3 api.py"