name: Python Test

on:
  push:
    branches:
      - main  # Change to your default branch name if it's different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests
      run: python test.py

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # EC2 instance public IP or DNS
        username: ${{ secrets.EC2_USERNAME }} # EC2 instance username
        key: ${{ secrets.EC2_PRIVATE_KEY }} # SSH private key for accessing EC2 instance
        port: ${{ secrets.EC2_PORT }} # SSH port, default is 22
        script: |
          cd ~/fastapi-cicd/
          git pull origin main
          pkill -f "python3 api.py"
          python3 api.py