name: Python Test

on:
  push:
    branches:
      - main  # Change to your default branch name if it's different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests
      run: python test.py

    - name: Update
      run: |
        chmod 600 ssh.em
        ssh -o StrictHostKeyChecking=no -i ssh.em ubuntu@ec2-18-201-138-117.eu-west-1.compute.amazonaws.com "cd ~/fastapi-cicd && git pull origin main && pkill -f 'python3 api.py'"

    - name: Deploy 
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh.em ubuntu@ec2-18-201-138-117.eu-west-1.compute.amazonaws.com "cd ~/fastapi-cicd && nohup python3 api.py > /dev/null 2>&1 & exit"

